#!/usr/bin/bash
#edits keybindings in configuration files for source engine based games to switch the keyboard layout from dvorak to qwerty
#17:17| <  falconindy> | "s@bind \"'\"@bind \"q\"@"
#17:17| <  falconindy> | or $'s@bind "\'"@bind "q"@'
#17:17| <  falconindy> | or 's@bind "'\''"@bind "q"@'

echo 'Converting binds for file '$1'...'

sed -r --file=./hl-dvork2qwerty.sed $1 > $1.new

echo 'Done.'